### ISSUE TITLE
Get /buckets response  with kind and owner arguments is not coherent

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/catalog#57]
With the following configuration : 
bucket1(owner:bot) containing an object with the kind "worklfow"
bucket2(owner:toto) containing an object with the kind "workflow"
bucket3(owner:bot) not containing an object with the kind "worklfow"

Get /buckets?owner=bot&kind=worklfow 
return bucket1 and bucket3

The response is neither a logic AND or OR. It seems that if owner parameter is passed, kind parameter is ignored.

**Comment by ShatalovYaroslav** [comment]
It's en expecting behavior.
From specification it was decided, that we will get all buckets, that satisfy the condition for owner bucket and kind of objects inside this bucket, but also returning empty buckets. Because for empty buckets, we don't no what kind of objects will be inside bucket.
Is bucket3 is empty in your case?

**Comment by MaelAudren** [comment]
The request will return the same response if bucket3 is empty or if it contains workflows with a kind which is not "workflow" .
